<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="laser_enabled" default="$(optenv CPR_LASER_ENABLED 0)" />
  <xacro:arg name="laser_xyz" default="$(optenv CPR_LASER_XYZ 0.2206 0.0 0.00635)" />
  <xacro:arg name="laser_rpy" default="$(optenv CPR_LASER_RPY 0.0 0.0 0.0)" />

  <xacro:arg name="realsense_enabled" default="$(optenv CPR_REALSENSE 0)" />
  <xacro:arg name="realsense_xyz" default="$(optenv CPR_REALSENSE_XYZ 0 0 0)" />
  <xacro:arg name="realsense_rpy" default="$(optenv CPR_REALSENSE_RPY 0 0 0)" />
  <xacro:arg name="realsense_mount" default="$(optenv CPR_REALSENSE_MOUNT_FRAME sensor_arch_mount_link)" />

  <xacro:property name="dogtooth_front_bumper_extend" value="$(optenv DOGTOOTH_FRONT_BUMPER_EXTEND 0)" />
  <xacro:property name="dogtooth_rear_bumper_extend" value="$(optenv DOGTOOTH_REAR_BUMPER_EXTEND 0)" />

  <xacro:arg name="robot_namespace" default="/" />
  <xacro:arg name="is_sim" default="false" />
  <!-- Included URDF/XACRO Files -->
  <!-- <xacro:include filename="$(find dogtooth_description)/urdf/decorations.urdf.xacro" /> -->
  <xacro:include filename="$(find dogtooth_description)/urdf/wheel.urdf.xacro" />

  <xacro:include filename="$(find dogtooth_description)/urdf/accessories/intel_realsense.urdf.xacro"/>
  
  <!-- Add Livox Lidar model -->
  <!--<xacro:include filename="$(find ros2_livox_simulation)/urdf/mid360.xacro" />-->

  <xacro:property name="M_PI" value="3.14159"/>

  <xacro:macro name="dogtooth" params="prefix">

    <!-- Base Size -->
    <xacro:property name="base_x_size" value="0.98740000" />
    <xacro:property name="base_y_size" value="0.57090000" />
    <xacro:property name="base_z_size" value="0.24750000" />

    <!-- Wheel Mounting Positions -->
    <xacro:property name="wheelbase" value="0.5120" />
    <xacro:property name="track" value="0.5708" />
    <xacro:property name="wheel_vertical_offset" value="0.03282" />

    <!-- Wheel Properties -->
    <xacro:property name="wheel_length" value="0.1143" />
    <xacro:property name="wheel_radius" value="0.1651" />

    <!-- Base link is the center of the robot's bottom plate -->

    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!-- <mesh filename="package://husky_description/meshes/base_link.dae" /> -->
          <mesh filename="file://$(find dogtooth_description)/meshes/chassis.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="${( dogtooth_front_bumper_extend - dogtooth_rear_bumper_extend ) / 2.0} 0 ${base_z_size/4}" rpy="0 0 0" />
        <geometry>
          <box size="${ base_x_size + dogtooth_front_bumper_extend + dogtooth_rear_bumper_extend } ${base_y_size} ${base_z_size/2}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 ${base_z_size*3/4-0.01}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size*4/5} ${base_y_size} ${base_z_size/2-0.02}"/>
        </geometry>
      </collision>
    </link>

    <!-- Base footprint is on the ground under the robot -->
    <link name="${prefix}base_footprint"/>

    <joint name="${prefix}base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}base_footprint" />
    </joint>

    <!-- Inertial link stores the robot's inertial information -->
    <link name="${prefix}inertial_link">
      <inertial>
        <mass value="46.034" />
        <origin xyz="-0.00065 -0.085 0.062" />
        <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
      </inertial>
    </link>

    <joint name="${prefix}inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}inertial_link" />
    </joint>

    <!-- IMU Link-->
    <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
    <link name="${prefix}imu_link1"/>
    <joint name="${prefix}imu_joint1" type="fixed">
      <origin xyz="$(optenv CPR_IMU1_XYZ 0 0 0)" rpy="$(optenv CPR_IMU_RPY 0 0 0)" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}imu_link1" />
    </joint>

    <link name="${prefix}imu_link2"/>
    <joint name="${prefix}imu_joint2" type="fixed">
      <origin xyz="$(optenv CPR_IMU2_XYZ 0 0 0.4)" rpy="$(optenv CPR_IMU_RPY 0 0 0)" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}imu_link2" />
    </joint>

    <!-- GPS Link-->
    <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
    <link name="${prefix}gps_link"/>
    <joint name="${prefix}gps_joint" type="fixed">
      <origin xyz="$(optenv CPR_GPS_XYZ 0 0 0)" rpy="$(optenv CPR_GPS_RPY 0 0 0)" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}gps_link" />
    </joint>

    <!-- Ultrasonic Link-->
    <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
    <link name="${prefix}ultrasonic_link1"/>
    <joint name="${prefix}ultrasonic_joint1" type="fixed">
      <origin xyz="$(optenv CPR_ULTRASONIC_XYZ 0 0 0)" rpy="$(optenv CPR_ULTRASONIC_XYZ 0 0 0)" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}ultrasonic_link1" />
    </joint>

    <link name="${prefix}ultrasonic_link2"/>
    <joint name="${prefix}ultrasonic_joint2" type="fixed">
      <origin xyz="$(optenv CPR_ULTRASONIC_XYZ 0 0 0)" rpy="$(optenv CPR_ULTRASONIC_XYZ 0 0 3.14)" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}ultrasonic_link2" />
    </joint>


    <joint name="${prefix}front_camera_joint" type="fixed">
        <origin xyz="1.2 0.0 0.6" rpy="0 0 0"/>
        <parent link="${prefix}base_link"/>
        <child link="${prefix}front_camera"/>
    </joint>

    <link name="${prefix}front_camera">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
            <geometry>
                <mesh filename="file://$(find dogtooth_description)/meshes/r200.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
            <geometry>
                <box size="0.012 0.132 0.020"/>
            </geometry>
        </collision>
    </link>

    <!-- Lidar -->
    <!--<xacro:mid360 name="livox_front" parent="base_link" topic="front_lidar/scan">
      <origin xyz="1.2 0.5 0.5" rpy="0 0 0"/>
    </xacro:mid360>-->

    <!--<xacro:mid360 name="livox_back" parent="base_link" topic="back_lidar/scan">
      <origin xyz="-1.2 -0.5 0.5" rpy="0 0 0"/>
    </xacro:mid360>-->

    <joint name="${prefix}front_camera_rgb_joint" type="fixed">
        <origin xyz="0.005 0.018 0.013" rpy="-1.57 0 -1.57"/>
        <parent link="${prefix}front_camera"/>
        <child link="${prefix}front_camera_rgb_frame"/>
    </joint>
    <link name="${prefix}front_camera_rgb_frame"/>

    <joint name="${prefix}front_camera_rgb_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="${prefix}front_camera_rgb_frame"/>
        <child link="${prefix}front_camera_rgb_optical_frame"/>
    </joint>
    <link name="${prefix}front_camera_rgb_optical_frame"/>

    <joint name="${prefix}front_camera_depth_joint" type="fixed">
        <origin xyz="0.005 0.028 0.013" rpy="-1.57 0 -1.57"/>
        <parent link="${prefix}front_camera"/>
        <child link="${prefix}front_camera_depth_frame"/>
    </joint>
    <link name="${prefix}front_camera_depth_frame"/>

    <joint name="${prefix}front_camera_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="${prefix}front_camera_depth_frame"/>
        <child link="${prefix}front_camera_depth_optical_frame"/>
    </joint>
    <link name="${prefix}front_camera_depth_optical_frame"/>

    <joint name="${prefix}back_camera_joint" type="fixed">
        <origin xyz="-1.2 0.0 0.6" rpy="0 0 3.14"/>
        <parent link="${prefix}base_link"/>
        <child link="${prefix}back_camera"/>
    </joint>

    <link name="${prefix}back_camera">
        <visual>
        <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
        <geometry>
            <mesh filename="file://$(find dogtooth_description)/meshes/r200.dae" />
        </geometry>
        </visual>
        <collision>
        <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
        <geometry>
            <box size="0.012 0.132 0.020"/>
        </geometry>
        </collision>
    </link>

    <joint name="${prefix}back_camera_rgb_joint" type="fixed">
        <origin xyz="0.005 0.018 0.013" rpy="-1.57 0 -1.57"/>
        <parent link="${prefix}back_camera"/>
        <child link="${prefix}back_camera_rgb_frame"/>
    </joint>
    <link name="${prefix}back_camera_rgb_frame"/>

    <joint name="${prefix}back_camera_rgb_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="${prefix}back_camera_rgb_frame"/>
        <child link="${prefix}back_camera_rgb_optical_frame"/>
    </joint>
    <link name="${prefix}back_camera_rgb_optical_frame"/>

    <joint name="${prefix}back_camera_depth_joint" type="fixed">
        <origin xyz="0.005 0.028 0.013" rpy="-1.57 0 -1.57"/>
        <parent link="${prefix}back_camera"/>
        <child link="${prefix}back_camera_depth_frame"/>
    </joint>

    <link name="${prefix}back_camera_depth_frame"/>

    <joint name="${prefix}back_camera_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="${prefix}back_camera_depth_frame"/>
        <child link="${prefix}back_camera_depth_optical_frame"/>
    </joint>
    <link name="${prefix}back_camera_depth_optical_frame"/>

    <link name="${prefix}lidar_link">
        <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.125"/>
        <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>

        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="0.0508" length="0.055"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="0.0508" length="0.055"/>
        </geometry>
        </visual>
    </link>

    <joint name="${prefix}lidar_joint" type="fixed">
        <parent link="${prefix}base_link"/>
        <child link="${prefix}lidar_link"/>
        <origin xyz="1.2 0 0.5" rpy="0 0 -1.5"/>
    </joint>

    <!-- dogtooth wheel macros -->
    <xacro:dogtooth_wheel wheel_prefix="${prefix}front_left">
      <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:dogtooth_wheel>
    <xacro:dogtooth_wheel wheel_prefix="${prefix}front_right">
      <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:dogtooth_wheel>
    <xacro:dogtooth_wheel wheel_prefix="${prefix}rear_left">
      <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:dogtooth_wheel>
    <xacro:dogtooth_wheel wheel_prefix="${prefix}rear_right">
      <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:dogtooth_wheel>

    <!-- add the intel realsense to the topbar if needed -->
    <xacro:if value="$(arg realsense_enabled)">
      <link name="realsense_mountpoint"/>
      <joint name="realsense_mountpoint_joint" type="fixed">
        <origin xyz="$(arg realsense_xyz)" rpy="$(arg realsense_rpy)" />
        <parent link="$(arg realsense_mount)"/>
        <child link="realsense_mountpoint" />
      </joint>
      <xacro:intel_realsense_mount prefix="camera" topic="realsense" parent_link="realsense_mountpoint"/>
    </xacro:if>

    <ros2_control name="${prefix}dogtooth_hardware" type="system">
      <hardware>
        <xacro:if value="$(arg is_sim)">
          <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </xacro:if>
        <xacro:unless value="$(arg is_sim)">
          <!-- <plugin>dogtooth_base/DogtoothHardware</plugin>
          <plugin>fake_components/GenericSystem</plugin>
          <param name="hw_start_duration_sec">2.0</param>
          <param name="hw_stop_duration_sec">3.0</param>
          <param name="wheel_diameter">0.3302</param>
          <param name="max_accel">5.0</param>
          <param name="max_speed">1.0</param>
          <param name="polling_timeout">10.0</param>
          <param name="serial_port">/dev/prolific</param> -->
        </xacro:unless>
      </hardware>
      <joint name="${prefix}front_left_wheel_joint">
        <command_interface name="velocity">
          <param name="min">-1</param>
          <param name="max">1</param>
        </command_interface>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>
      <joint name="${prefix}rear_left_wheel_joint">
        <command_interface name="velocity">
          <param name="min">-1</param>
          <param name="max">1</param>
        </command_interface>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>
      <joint name="${prefix}front_right_wheel_joint">
        <command_interface name="velocity">
          <param name="min">-1</param>
          <param name="max">1</param>
        </command_interface>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>
      <joint name="${prefix}rear_right_wheel_joint">
        <command_interface name="velocity">
          <param name="min">-1</param>
          <param name="max">1</param>
        </command_interface>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>
    </ros2_control>

  </xacro:macro>

</robot>
